url: https://fbarde.github.io
baseurl: /ADA_Data_Story/

# Site settings
title: flagADA22
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Flore Barde
  pic: flore
  position: Master Life Sciences
  social:
    - title: envelope
      url: mailto:flore.barde@epfl.ch
    - title: github
      url: https://github.com/fbarde
    - title: linkedin
      url: https://www.linkedin.com/in/flore-barde-75753a24a/

- name: Manon Béchaz
  pic: manon
  position: Master Computational Sciences
  social:
    - title: envelope
      url: mailto:manon.bechaz@epfl.ch
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Zoé Jeandupeux
  pic: zoe
  position: Master Physics
  social:
    - title: envelope
      url: mailto:zoe.jeandupeux@epfl.ch
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Killian Rigaux
  pic: killian
  position: Master Physics
  social:
    - title: envelope
      url: mailto:killian.rigaux@epfl.ch
    - title: github
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
